### ISSUE TITLE
config.cmake is missing

### ISSUE THREAD

**Issue by Lurkrazy** [HPCRL/Ansor-AF-DS#1]

**Comment by badeok0716** [comment]
Hi, is there any plan for releasing the missing "config.cmake" file?

**Comment by Lurkrazy** [comment]
Hi, please make sure that both **CUDA** and **LLVM** are installed on your system. You can verify this by running the following commands in your terminal:

```
llvm-config --version
nvcc --version
```

The CUDA and LLVM are required in the config.cmake, please use the following command to build from the source code:
```
git clone git@github.com:HPCRL/Ansor-AF-DS.git --recursive
cd Ansor-AF-DS/benchmarks/Ansor_AF_DS

export TVM_HOME=$PWD && export PYTHONPATH=$TVM_HOME/python
mkdir -p build && cd ./build

cp "$TVM_HOME/cmake/config.cmake" ./

sed -i 's/set(USE_CUDA OFF)/set(USE_CUDA ON)/' config.cmake
sed -i 's/set(USE_LLVM OFF)/set(USE_LLVM ON)/' config.cmake

cmake ..
make -j8
```
